name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello Dave." 
      - name: Print goodbye
        run: echo "See you later, Dave."
